name = "SecretSanta"
uuid = "bb3d3a65-b032-5cdd-a073-dfed7b606c01"
authors = ["Byron Tasseff"]
repo = "https://github.com/tasseff/SecretSanta.jl"
version = "0.2.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SMTPClient = "c35d69d1-b747-5018-a192-25bc5e63c83d"

[compat]
Dates = "1.6 - 1"
HiGHS = "~1"
JSON = "~0.21, ~1"
JuMP = "~0.22, ~0.23, ~1"
Random = "1.6 - 1"
SMTPClient = "~0.3, ~0.6"
julia = "1.6 - 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
